DOC-4728
couchbase/docs-ui-old pull request #49
Opened 2019-02-05 11:42 UTC by jamiltz

https://issues.couchbase.com/browse/DOC-4728

2019-02-05 18:50 UTC, jamiltz commented
@mojavelinux I think this PR is ready for review (I've written a summary of changes on the first PR comment).
Would be great to your review on it.
Preview src page: https://deploy-preview-49--cb-docs-ui.netlify.com/tutorials.html

2019-02-07 23:14 UTC, mojavelinux requested changes

2019-02-07 23:14 UTC, mojavelinux commented on src/partials/footer-scripts.hbs
> +<script src="https://cdn.jsdelivr.net/mark.js/8.6.0/mark.min.js"></script>
I strongly recommend bundling all JavaScript as part of site.js (like was done with docsearch) instead of reaching out to a CDN (which gives away your tracking data and likely violates GDPR).

2019-02-07 23:14 UTC, mojavelinux commented on src/css/doc.css
> +/** CSS rules for tiles on the tutorial list page **/
I don't think the styles for the tutorials overview pages should be in the doc.css file. These belong in the home.css file because they are a specialization of the home page.

2019-02-07 23:14 UTC, mojavelinux commented on src/partials/body-tutorials.hbs
> +                        placeholder="Search Couchbase Tutorials"
I would change this placeholder text to "Find a Couchbase Tutorial" so that you don't have two different "search" boxes on the page.

2019-02-07 23:14 UTC, mojavelinux commented on src/partials/body-tutorials.hbs
> +      </nav>
The indentation here is not consistent. I see 3 spaces in some cases instead of 2.

2019-02-07 23:14 UTC, mojavelinux commented on src/layouts/tutorials.hbs
> +    <link rel="canonical" href="{{{site.url}}}">
I generally recommend not indenting after a conditional (because it's not a true indentation opportunity).

2019-02-07 23:14 UTC, mojavelinux commented on src/css/site.css
> +@import "tutorials.css";
Why are some of the styles for tutorials in doc.css and some in tutorials.css? I recommend reusing home.css since tutorials is a specialization of the home page.

2019-02-07 23:14 UTC, mojavelinux commented on preview-site-src/tutorials.adoc
> +[.title]
I recommend always leaving a blank line after a section title.

2019-02-07 23:14 UTC, mojavelinux commented on preview-site-src/tutorials.adoc
> +xref:tutorials:mobile-travel-sample:swift/design/data-modeling.adoc[Deploy Couchbase in Kubernetes]
It doesn't feel right to me to use a "title" role for the tutorial heading. This should either be a discrete heading or a block title.

2019-02-07 23:18 UTC, mojavelinux commented
@jamiltz I think this is a great start. I left some comments in the review. My main concern, however, is that the style isn't quite consistent with the brand guidelines. It mostly has to do with the spacing / padding, though the font sizes seem a bit off too. I would strongly recommend that you have the web design team look this over and make adjustments to the styles so that it aligns more with the .com site, for example https://www.couchbase.com/partners/find-a-partner. Ideally, the experience should be seamless. And we should expect that they are involved, because this is their area of expertise.

2019-02-16 12:53 UTC, jamiltz commented on src/partials/footer-scripts.hbs
> +<script src="https://cdn.jsdelivr.net/mark.js/8.6.0/mark.min.js"></script>
https://github.com/couchbase/docs-ui/pull/49/commits/906f65e52f447c00bb424e83d263f58a64015ae5

2019-02-16 12:58 UTC, jamiltz commented on src/css/doc.css
> +/** CSS rules for tiles on the tutorial list page **/
OK. I've moved the changes in `doc.css` over to `home.css` https://github.com/couchbase/docs-ui/pull/49/commits/4408b32a29ef2db8ada5a15a0060e933d9ec0286

2019-02-16 12:59 UTC, jamiltz commented on src/partials/body-tutorials.hbs
> +                        placeholder="Search Couchbase Tutorials"
Good point, I've updated the placeholder https://github.com/couchbase/docs-ui/pull/49/commits/2ea713b4d41ff0983700efdbd4f2ab78b56ccdc6

2019-02-16 13:00 UTC, jamiltz commented on src/partials/body-tutorials.hbs
> +      </nav>
Fixed https://github.com/couchbase/docs-ui/pull/49/commits/4595082a444834e7df19b8d1a14586c855726532

2019-02-16 13:02 UTC, jamiltz commented on src/layouts/tutorials.hbs
> +    <link rel="canonical" href="{{{site.url}}}">
Fixed https://github.com/couchbase/docs-ui/commit/4595082a444834e7df19b8d1a14586c855726532

2019-02-16 13:04 UTC, jamiltz commented on src/css/site.css
> +@import "tutorials.css";
Yes good point, done in https://github.com/couchbase/docs-ui/pull/49/commits/b748a7527cb72fdd1a3fa067b1837b8bb0701a73

2019-02-16 13:09 UTC, jamiltz commented on preview-site-src/tutorials.adoc
> +[.title]
Yes I usually do as well. For some reason I thought `docs-ui` asciidoc files would be different but there's not reason for that to be. Fixed in https://github.com/couchbase/docs-ui/pull/49/commits/27afb5fdfbed0341f31465ecf94e92caf2c71e6f

2019-02-16 21:37 UTC, jamiltz commented on preview-site-src/tutorials.adoc
> +xref:tutorials:mobile-travel-sample:swift/design/data-modeling.adoc[Deploy Couchbase in Kubernetes]
Yes! I had not thought about making the xref a discrete heading. I've indented other headers accordingly. https://github.com/couchbase/docs-ui/pull/49/commits/20d2f31260143c1175a1e8926ab09bd1fb7c1f1a

2019-02-16 21:58 UTC, jamiltz commented
@mojavelinux Thanks for the thorough review! I've addressed the review comments, received the web team's recommendations and applied them.

I'd appreciate a review of the fix to bundle `mark.js` in the site output (commit https://github.com/couchbase/docs-ui/commit/906f65e52f447c00bb424e83d263f58a64015ae5#diff-e1d72f8220e801ddc8e7445a441626ef). Is that how it should be done? Thanks!

2019-02-19 19:31 UTC, jamiltz commented
@mojavelinux is there a way in Asciidoc to create a new parent div in the output? I'm currently using `===== {empty}` which outputs the following (with an empty `h5` element):

```
<div class="sect5">
  <h5></h5>
</div>
```

2019-02-21 21:24 UTC, mojavelinux commented
@jamiltz I'm looking over the updates now. From your comments, I anticipate it's already in great shape!

> @mojavelinux is there a way in Asciidoc to create a new parent div in the output? I'm currently using `===== {empty}` which outputs the following (with an empty `h5` element):

That's certainly one way. Another is an open block, though that can conflict with nested / included content. Yet another solution is to use an example block with a delimiter length of more than 4 (such as 6) so it doesn't conflict with nested / included content.

Ultimately, this is the solution we want: https://github.com/asciidoctor/asciidoctor/issues/1121. But there are reasons why that has to remain on hold.

2019-02-21 22:00 UTC, mojavelinux commented on src/partials/footer-scripts.hbs
> +<script src="https://cdn.jsdelivr.net/mark.js/8.6.0/mark.min.js"></script>
Excellent. Though you're missing the bundle step in the build task. I'll notate the line.

2019-02-21 22:01 UTC, mojavelinux commented on src/partials/body-tutorials.hbs
> +                        placeholder="Search Couchbase Tutorials"
There's still an extra "s". It should be "Find a Couchbase Tutorial" instead of "Find a Couchbase Tutorials".

2019-02-21 22:25 UTC, mojavelinux requested changes
I requested a few small changes...and then one substantive change with regard to the design of the tiles.

2019-02-21 22:25 UTC, mojavelinux commented on src/layouts/tutorials.hbs
> +  {{> head-first}}
Handlebars includes should always be aligned with the left margin (to avoid the content it includes from being indented).

```
<head>
{{> head-first}}
  <title>Couchbase Tutorials</title>
```

2019-02-21 22:25 UTC, mojavelinux commented on src/partials/body-tutorials.hbs
> +        {{{ page.contents }}}
Don't include space inside the Handlebars. Also, don't indent included content. Otherwise, Handlebars likes to add that indentation to every line (unless a special option is passed to Handlebars, which may or may not be set).

```html
      <article class="doc">
{{{page.contents}}}
      </article>
```

2019-02-21 22:25 UTC, mojavelinux commented on src/partials/footer-scripts.hbs
> +<script async src="{{uiRootPath}}/js/vendor/mark.js"></script>
You also need to add mark.js to tasks/build.js

```js
    vfs
      .src('js/vendor/{docsearch,highlight,mark}.js', Object.assign({ read: false }, opts))
```

2019-02-21 22:25 UTC, mojavelinux commented on src/partials/body-tutorials.hbs
> +              <input
One idea that I think would really improve the UX is to automatically scroll the search box to the top of the visible area when the user starts to type in the search field. This will leave room for the results below (without having to fix the scrolling of the page).

2019-02-21 22:25 UTC, mojavelinux commented on src/css/home.css
> +  margin-right: 20px;
I strongly recommend against using px units. Not only do rems (or ems) lend themselves better to scaling, they also encourage the use of consistent values. It's too tempting with px to just use any number, then you end up with sizes and spaces that don't have stepwise gradation.

2019-02-21 22:25 UTC, mojavelinux commented on src/css/home.css
> +  border: 1px solid lightgrey;
I'm still not convinced about the design of the tiles. The lightgrey border especially sets of alarm bells for me because that's not coming from the palette of colors defined in vars.css (and it's also built-in color, which is almost guaranteed to be off brand).

I think the tiles should build on the design from one of these:

* persona tiles on https://docs.couchbase.com/home/index.html
* Featured Partners on https://www.couchbase.com/partners/find-a-partner
* Features on https://www.couchbase.com/products/developer-sdk
* Solve your toughest NoSQL adoption and production challenges on https://www.couchbase.com/products/n1ql

The persona tiles would be my recommendation.

I do understand that you have more content to display than in those tiles. So there's certainly some augmentation that needs to happen. But when you design the AsciiDoc, try to make sure to maintain the integrity of the AsciiDoc without making it cater too much to the HTML output. You can then use CSS to move content around.

For example, I think "Components" and "Languages" should be a description list, not section titles. That would then eliminate the need for the blank parent section.

2019-02-21 22:27 UTC, mojavelinux commented
I left a review comment about how you can remove at least one of the blank sections. Instead of a blank section around the Components and Languages, you can use a description list.

2019-02-22 12:28 UTC, jamiltz commented on src/layouts/tutorials.hbs
> +  {{> head-first}}
OK I'll try to remember from now on. Fixed in https://github.com/couchbase/docs-ui/pull/49/commits/4b2305f591514f502403aa891374596a1310754e

2019-02-22 12:28 UTC, jamiltz commented on src/partials/body-tutorials.hbs
> +        {{{ page.contents }}}
Fixed in https://github.com/couchbase/docs-ui/pull/49/commits/0d0f4698e8eccf91c6487a3dbd8ffe5285eb550d

2019-02-22 12:28 UTC, jamiltz commented on src/partials/footer-scripts.hbs
> +<script async src="{{uiRootPath}}/js/vendor/mark.js"></script>
Fixed in https://github.com/couchbase/docs-ui/pull/49/commits/98be6f49fcbb4da174ea5faa761fc70d4ef742dd

2019-02-22 12:31 UTC, jamiltz commented on src/partials/body-tutorials.hbs
> +              <input
Good idea! I've filed a ticket (as an improvement) to keep that feedback in mind https://issues.couchbase.com/browse/DOC-4815. Do you have a recommendation for how to do that on our site? (should I use vanilla JavaScript?)

2019-02-22 12:32 UTC, jamiltz commented on src/css/home.css
> +  margin-right: 20px;
Ok good to know! Converted `px`s to `rems` in https://github.com/couchbase/docs-ui/pull/49/commits/e7d275c564fe276f20965be40f58dd510bbda719

2019-02-22 12:37 UTC, jamiltz commented on src/css/home.css
> +  border: 1px solid lightgrey;
> I'm still not convinced about the design of the tiles. The lightgrey border especially sets of alarm bells for me because that's not coming from the palette of colors defined in vars.css (and it's also built-in color, which is almost guaranteed to be off brand).

Good point, I've changed it to the official color https://github.com/couchbase/docs-ui/pull/49/commits/545c017b521b87f0232afa1b5ca3bcae04d8a14b

> I think the tiles should build on the design from one of these:
>
> * persona tiles on https://docs.couchbase.com/home/index.html
> * Featured Partners on https://www.couchbase.com/partners/find-a-partner
> * Features on https://www.couchbase.com/products/developer-sdk
> * Solve your toughest NoSQL adoption and production challenges on https://www.couchbase.com/products/n1ql
>
> The persona tiles would be my recommendation.
>
> I do understand that you have more content to display than in those tiles. So there's certainly some augmentation that needs to happen. But when you design the AsciiDoc, try to make sure to maintain the integrity of the AsciiDoc without making it cater too much to the HTML output. You can then use CSS to move content around.

Yes, I think we should consider aligning with the persona tiles. Will mention it to the docs team. I've filed a ticket to track further https://issues.couchbase.com/browse/DOC-4817

> For example, I think "Components" and "Languages" should be a description list, not section titles. That would then eliminate the need for the blank parent section.

Filed a ticket to re-work it https://issues.couchbase.com/browse/DOC-4816

2019-02-22 12:41 UTC, jamiltz commented
> I left a review comment about how you can remove at least one of the blank sections. Instead of a blank section around the Components and Languages, you can use a description list (though you may still run into a problem that description list items themselves aren't wrapped in a containing element, so they can be hard to layout).

OK. I've added that feedback to https://issues.couchbase.com/browse/DOC-4816 (I'm not sure how to layout Components and Languages if there is no containing element)

2019-02-22 12:48 UTC, jamiltz commented
Thanks for the re-review. I've addressed the change requests and filed JIRA tickets where I will need more time. I'll merge the PR 🎉

2019-02-22 12:49 UTC, merged

2019-03-09 09:13 UTC, mojavelinux commented on src/partials/body-tutorials.hbs
> +              <input
I would definitely use vanilla JavaScript (as it's pretty good these days). I would catch the first keyup event after focus, compute the offset top of the search box, then use window.scrollTo() to get there.

2019-03-12 10:38 UTC, jamiltz commented on src/partials/body-tutorials.hbs
> +              <input
Great, I've added the suggestion to the JIRA ticket. Thank you.